spring:
  application:
    name: remoting-amqp-client
  rabbitmq:
    dynamic: true
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  path: ./${spring.application.name}/logs
  file: ./${spring.application.name}/logs/${spring.application.name}.log
  level:
    org.springframework.amqp: WARN
    org.springframework.scheduling: WARN
