spring:
  rabbitmq:
    dynamic: true
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    sender:
      type: rabbit

logging:
  path: ./logs
  file: ./logs/${spring.application.name}.log
  level:
    org.springframework.amqp: WARN
    org.springframework.scheduling: WARN
